### ISSUE TITLE
LICENSE file?

### ISSUE THREAD

**Issue by jlbribeiro** [MercuryTechnologies/looking-glass-viewer#1]
First of all, thank you @lf- for making this code available, found the viewer quite useful already!

I want to hack it a bit, to customize some things (graph layout, mainly, but also the way it "inits" the graph), while making use of the overall structure. Although I found it via your [NixCon2022 blog post](https://jade.fyi/nixcon2022/) on debugging closure sizes, which mentions this project being "open-source under under the MIT license", I couldn't find an explicit mention to the license (edit: except the `package.json`).

Would you consider adding a `LICENSE` file to make it _more_ explicit, of whichever license you chose?
Once again, thank you for this repo!

**Comment by lf-** [comment]
omg lol oops. yes it was intended to be MIT all along. @parsonsmatt would you be able to add one?

**Comment by jlbribeiro** [comment]
Thank you. @prikhi!
